[phases.setup]
nixPkgs = [
  "nodejs",
  "pnpm",
  "python3",
  "gcc",
  "gnumake",
]

[variables]
PYTHON = "/usr/bin/python3"

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install",
]

[phases.build]
cmds = [
  "pnpm --filter @wisdom/api build",
]

[start]
cmd = "pnpm --filter @wisdom/api start"
