const BODY = "healing-code-cards-body-deck";
const MIND = "healing-code-cards-mind-deck";
const ENERGY = "healing-code-cards-energy-deck";
const SOURCE = "healing-code-cards-source-deck-body-set";

export const LIVE_HEALING_CODE_CARD_SLUGS = [BODY, MIND, ENERGY, SOURCE];

export interface RecoveredCardTestimonial {
  customerName: string;
  location: string | null;
  title: string;
  testimonialText: string;
  sourceLabel: string;
  contextLabel: string;
  sortOrder: number;
  productSlugs: string[];
}

export const RECOVERED_CARD_TESTIMONIALS: RecoveredCardTestimonial[] = [
  {
    customerName: "Kathy Latta",
    location: null,
    title: "Headache Eliminator Experience",
    testimonialText: "I usually never get headaches. Today I had a dull, achy, pounding headache with part of my scalp sensitive to the touch. I gazed at the Headache Eliminator card for a minute and then put the card and the 20x amplifier card on my head and put a beanie over them. Then I laid town and ended up taking a 2.5 nap. When I woke up, I felt like a million bucks. No headache, and no sensitive scalp. Wow! I love these cards and use them for different maladies all the time and I use them on my cats too!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 10,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Alan Cohen",
    location: null,
    title: "Sleep Purifier Experience",
    testimonialText: "I normally wake up feeling tired and groggy. I also wake up feeling intense energy in my head like I am still in another dimension. It takes me a little while to come back into this reality. I laid down in bed last night and meditated with the sleep purifier card and an amplifier card behind it on my heart for a while. I was amazed at the difference when I woke up this morning feeling very clear and refreshed at 4 a.m. ready to go.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Energy Deck",
    sortOrder: 11,
    productSlugs: [ENERGY],
  },
  {
    customerName: "Carol Rebers",
    location: null,
    title: "Mind Deck Manifestation Experience",
    testimonialText: "I used the Mind Deck Manifestation Enhancer card a few days ago to see more \"starcraft\" or extraterrestrials in the sky day or night, that was the message that I had written and placed on my side table, the other night I was out in my courtyard while watching a local helicopter flying around and then went away, a huge white star suddenly appeared out of nowhere and was moving and coming towards me, I watched it for a minute and then it passed me and disappeared into the night. My manifestation came true with these cards. Thank you so much Brad. I'm keeping my message on my card just in case I see more.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Mind Deck",
    sortOrder: 12,
    productSlugs: [MIND],
  },
  {
    customerName: "Carolann Smith",
    location: null,
    title: "Energy Deck Experience",
    testimonialText: "I have been using the Positive Polarity Collector card and the Negative Polarity Receiver card (Energy Deck). I placed the Positive Polarity Receiver where my sternum is located, and the Negative Polarity Receiver on the area where my bladder is, and it works amazingly. I have a problem when my anxiety level gets high and it affects my bladder making me have to go to the bathroom frequently. The cards work wonders and my bladder isn't doing that anymore. Thank you so much for creating all of these wonderful cards through the power of spirit.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Energy Deck",
    sortOrder: 13,
    productSlugs: [ENERGY],
  },
  {
    customerName: "Jan-Christian",
    location: null,
    title: "Energy Code Cards Experience",
    testimonialText: "This is my first time using the Energy code cards. I'm going to describe my experience. Due to a herniated disc, I've suffered terrible back pains for years. Mornings being the worse.. I've tried everything from acupuncture, pain relief patches, etc. but nothing has worked. Since I ordered the cards (actually never used them until I watched Brad's polarity cards video), I gave it a try for 10 minutes... The pain really went away! I couldn't believe it! Yet, the pain came back the next day..., but milder though. So I started a plan working everyday with those cards, placing them as Brad mentions. It's been 3 days now and the pain is diminishing, getting lesser, feeling better and better. Thank you so much Brad for being here on this Earth sharing with your fellow beings.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Energy Deck",
    sortOrder: 14,
    productSlugs: [ENERGY],
  },
  {
    customerName: "Lisa V.",
    location: null,
    title: "Body, Mind & Energy Deck Experience",
    testimonialText: "I am truly very excited to share my most recent experience with the healing code cards. This past week during this month of September, I had reconstructive facial surgery. When I got home, I wanted to heal myself quickly and get rid of pain so I pulled out the body deck. I work with these cards in my own unique way where I spread them out like a fan face down. I run my hand over them to feel which ones buzz /vibrate or heat up. The cards that I turned were cartilage enhancer, blood enhancer, skin enhancer, bone enhancer, pain eliminator, stomach enhancer and 10x amplifier For the procedure I had, these were literally THE perfect cards!!! (stomach enhancer came up because of the antibiotics that I had to take for a few days) I'm being very specific with sharing this because these cards are absolutely alive. They communicate with my body and this happens every time. Just mind-blowing and magical !! They have been a very significant and beautiful part of my journey over the last few years. I also have the mind and energy deck and love them as well.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body, Mind & Energy Decks",
    sortOrder: 15,
    productSlugs: [BODY, MIND, ENERGY],
  },
  {
    customerName: "Carolann Smith",
    location: null,
    title: "Mind Deck Experience",
    testimonialText: "I have been using the mind deck cards ,I use the brain emotional releaser, spirit light purifier, and lucid dream stabilizer every night since I suffer from anxiety, I have been sleeping much better and have such a calmness. I remember my dreams so clearly and my psychic senses are getting much better.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Mind Deck",
    sortOrder: 16,
    productSlugs: [MIND],
  },
  {
    customerName: "Steve Power",
    location: null,
    title: "Body Deck Experience",
    testimonialText: "After using the Body Deck cards for a week I began to feel improvement in the body areas that I had focused the energies on. I continue to use the Capture Method as it seems very easy and effective.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 17,
    productSlugs: [BODY],
  },
  {
    customerName: "Linda Jud",
    location: null,
    title: "Energy Deck Polarity Experience",
    testimonialText: "I work with all the card decks and especially enjoy Brad's latest edition, the energy deck. My favourites are the positive and negative polarity receivers (in the Energy Deck). They remove headaches or other ailments within minutes!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Healing Code Cards family",
    sortOrder: 18,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Sandra Sederstrom",
    location: null,
    title: "Sinus Enhancer Experience",
    testimonialText: "I have had allergies for many years, taking medications to be able to function everyday. The Sinus Enhancer card changed all of that in one week I didn't need any medication to be able to breathe. These cards are amazing, I use them all the time for myself and friends and family. thank you for the Healing Code Cards.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 19,
    productSlugs: [BODY],
  },
  {
    customerName: "Jerry Hildebrand",
    location: null,
    title: "Muscle Enhancer Experience",
    testimonialText: "(I) left the muscle enhancer card on my picture and have not had back muscle problems this year for the first time! THANK YOU BRAD.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 20,
    productSlugs: [BODY],
  },
  {
    customerName: "Joe",
    location: null,
    title: "Sinus Enhancer Experience",
    testimonialText: "These Healing Code cards are just Amazing. Already helped me heal my allergies which nothing else could help. My allergies had become so bad that I developed bleeding nose almost every day. I used The Sinus Enhancer card every day for about a week. After the first day I noticed that my allergies were not as bad as usual and my nose bleeds decreased as well. After the first week I was in tears not because of allergies but because I could finally breathe so well without any allergic reactions. Also my nose bleeds stopped completely. I also used the Headache relief card and was surprised that within approximately 10 minutes I could not feel my head pounding any longer. These cards have already helped me so much which I am so grateful to Brad for creating such technology. I believe these cards are essential for every home. Brad thank you so much for this and I can't wait for the new Mind deck to become available!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 21,
    productSlugs: [BODY],
  },
  {
    customerName: "Jenna",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "I love these cards. Definitely one of my favourite tools for healing. Even my 8 year son was startled by the energy of the cards at first and he loves them. I use during meditation, or place them and direct the energy into my drinks and food. I'm sure there are many ways to utilise these cards and I'm having fun figuring out new ways. For example, I've just had my fourth child and I know the healing process very well for the uterus and the surround areas. I used the reproductive card and another one (I forget which one at the moment) and this is the quickest recovery I've ever had. And that says something because it's my fourth time!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 22,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Andrea Infante",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "These cards are powerful when you use them with a pendulum. I’m a huge pendulum user so they come in handy in a time of need. They’re also very powerful to lay on your body and just meditate and let the energy heal.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 23,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Kathryn Beck",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "As true with all things, you get out what you put in. These cards, if you allow it, will help your body heal. I had pain in my hands from years of keyboard work, after using the cards, my hands are pain free. Brad Johnson is very good at helping you work through your traumas to lead you to a happier, healthier life.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 24,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Angel 333",
    location: null,
    title: "Body & Mind Deck Experience",
    testimonialText: "I wanted to send you a big THANK YOU for creating both the Body and Mind healing decks through the guidance of Spirit. I absolutely love them. During co-vid-19 I used the Virus eliminator card daily, and had it beside my bed for peace of mind. It helped keep the fear away. I have utilized so many of the others also, for a variety of purposes. My favorite one is the Love Energy card. After using the Virus card on my fresh food, I use the Love Energy card to replace what is lost and increase it's vibration. THANK YOU AGAIN FOR EVERYTHING!!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body & Mind Decks",
    sortOrder: 25,
    productSlugs: [BODY, MIND],
  },
  {
    customerName: "David Griffith",
    location: null,
    title: "Virus Eliminator Experience",
    testimonialText: "There was a lot of skepticism but having always had an open mind, what the heck let's see. Now the other night with all the virus fear porn the virus eliminator was an obvious choice figuring why not get some protection. Well, fortunately, sickness has been a stranger to me for decades as I work at being healthy. So in using the virus eliminator, added the 10x amplifier card behind it. Looked at the cards for 60 seconds and then laid in bed with the cards on my chest. Wow! is all that can be said. My body felt like it was in a dry sauna with the temp at max. The metal that came out of my body onto the tongue was very real and astounding. Don't know how these cards work and don't care because they work. As the Monkees once sang \"I'm a believer\".",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 26,
    productSlugs: [BODY],
  },
  {
    customerName: "Catalin Nastasa",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "I cant emphasize what a breakthrough these cards are. At first when I got them their energy was so powerful. The whole deck is so powerful. Each card has their own specific energy and healing properties. I have to take them step by step, one by one one day after another. I so much appreciate Brad for coming up with this idea of the healing cards.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 27,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Rowena Dumagan",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "Two weeks ago, my 2 pet dogs suddenly got ill and then the other one had died after 3 days. The vet doc told me that they got a virus. I worried very much if my other dog would also die. His two eyes were beginning to become blind. Then I suddenly thought to use your Healing Code Cards on my pet. I charged his drinking water with the Immune enhancer and the Vitality Enhancer [Free cards] everyday. Wow! surprisingly after 2 days my dog is beginning to regain his health and begin to eat his food. And not only that, his blindness had been cured. Oh Brad I'm so very thankful your Healing Code Cards! It also helped my family to maintain their good health!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 28,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Chris Cleary Petit",
    location: null,
    title: "Eye Enhancer Experience",
    testimonialText: "I'm using my healing code cards daily and absolutely loving them and tell my friends about them!!! I'm no longer wearing my glasses with the assistance of the Eye Enhancer card.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 29,
    productSlugs: [BODY],
  },
  {
    customerName: "Helen Davey",
    location: null,
    title: "Virus Eliminator Experience",
    testimonialText: "I’ve been using the Virus eliminator for a month, and had a dramatic clearance from my sinuses after 36 hrs. I’ve been using the free online card called the metabolism enhancer for 2 weeks and have noticed a steady half pound weight loss each wk and also cut back on sugars and carbs. I’m feeling more energetic, motivated and happy to move. I’m 72 so this is very helpful at a time in my life when it’s not easy to lose weight.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 30,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Patrick Wise",
    location: null,
    title: "Major Organ Card Experience",
    testimonialText: "After using all of the Healing Code Cards for about a month I now use the Major Organ card daily and I've noticed definite improvements in my health and sense of wellbeing. In one instance my entire family got a severe cold but I only had mild sniffles for one day!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 31,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Conny Damman",
    location: null,
    title: "Pain & Skin Card Experience",
    testimonialText: "I hurt my ankle so bad and also my knees and hand. On one knee I had a wound. I started working with the pain card. I was astonished that I could walk within 1.5 days. I worked with the skin card for my knee. The wound healed very well and quickly. Amazing these healing code cards, what a power. So happy with it!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 32,
    productSlugs: [BODY],
  },
  {
    customerName: "Fred Kim",
    location: null,
    title: "Brain, Muscle & Sinus Experience",
    testimonialText: "There's this memory game that I've struggled to get past a certain level. However, after using the brain enhancer only once, I ended up breaking that threshold. Now I'm consistently reaching higher levels on a daily basis. Concrete evidence of this card working almost immediately and the first one I ever used. Needless to say, I was staggered. Secondly, I've pulled a muscle during a workout session so I used the muscle enhancer to, hopefully, alleviate the pain. It did more than that, the problem was gone in a matter of minutes. I use this card regularly as well, and it seems to help with recovery and performance. Thirdly, I had a stuffy nose that was bugging me so I used the sinus enhancer and it worked almost instantly. I could breath normally again with no need to constantly blow my nose, lol. Even more amazing is the following day, when the stuffy nose returned with a vengeance by causing me to sneeze every few minutes. It was insufferable, I went to use the sinus enhancer again which helped, but not as much as I hoped for. As the amount of tissues I went through increased, I realized there's another card in the deck that I can use: the virus eliminator. I mean of course, right? I paired this card with the sinus enhancer again and I felt my sickness slowly dissipate until it was completely gone within a couple of hours. Quite the relief. I've been using several other cards with their own benefits but these have been the most noteworthy thus far. Absolutely amazing product by Brad, thank you so much for your work!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 33,
    productSlugs: [BODY],
  },
  {
    customerName: "David Violette",
    location: null,
    title: "Joint & Cartilage Card Experience",
    testimonialText: "I am sharing my experience thus far with the healing code cards because I’m having some results that were quite unexpected. Though I don’t have any serious health conditions with internal organs or disease, I have had an ongoing problem with osteoarthritis pain in my right knee and both shoulders in the rotator cuff area. So to relieve symptoms of stiffness, soreness, etc., I chose the Joint Enhancer, Stiffness Eliminator, Cartilage Enhancer, Muscle Enhancer, and Pain Eliminator to begin my use of the cards. I have been using them visually in the mornings and before bed at night, mostly---but now also during the day due to what’s been happening. Last night, I went to the health club where I exercise, and noticed when I was exercising on the butterfly pectoral machine for the chest, that having my arms outstretched to the sides was giving me no discomfort in my shoulders as was usual, and this was surprising. I then noticed as I moved my shoulders in a circular motion that they were much more limber with minimal stiffness. Curiously, I decided to test this further by going to the machine for lateral pull-downs, which requires reaching up with both hands and pulling the bars down in front of me, and this of course exercises the lat muscles. But I haven’t been able to do this exercise in years, even when I tried to force myself to pull the bars down even one time, the strain was too much and I couldn’t do it. However, last night I was able to reach up almost effortlessly, and pull down the bars with only minimal discomfort on the left shoulder. I was able to do 3 sets of this exercise at a moderate weight resistance, and I was astonished! You can mark my words when I tell you, I have been physically unable to do this kind of exercising, or even raise my arms that high in over 5 years. Tonight I went back to try it again, and now it’s even easier!! So this experience is quite unprecedented, I assure you, and I will want to post further updates about this phenomenon as it progresses. You have done a most formidable effort on this project of the healing cards, and I thank you!!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 34,
    productSlugs: [BODY],
  },
  {
    customerName: "Chyrese Soubasis",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "Within the first 30 minutes I could sense small parts of my physical body changing and shifting, such as several of my teeth. I use many alternative healing devices such as a rife machine, Isis pendulums, and bio-geometry methods, but none of those have offered the instant knowing that a healing and change is taking place. I intend to be very mindful when using these cards, as they require my presence. These cards may be the most powerful healing device I have used.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 35,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Katy Toma Mummager",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "Powerful amazing cards! For everyday use!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 36,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Darlene Johnston",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "Wow, amazing! I can see energy dancing around in the center of the card! I am so grateful and excited to be able to receive a deck of these cards! Thank you so much!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 37,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
  {
    customerName: "Nicola Bourne",
    location: null,
    title: "Lungs Enhancer Experience",
    testimonialText: "I used the Lungs Enhancer card last night as I was wheezy and needed my inhaler. Guess what? Within 5 mins of looking at the card for about 1.5 minutes I didn’t need my inhaler!",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding the Body Deck",
    sortOrder: 38,
    productSlugs: [BODY],
  },
  {
    customerName: "Bai Su",
    location: null,
    title: "Healing Code Cards Experience",
    testimonialText: "Wow I just used a few cards to relieve and heal my recent tiredness. Works amazing! I feel energized again at 1.32 am.",
    sourceLabel: "Healing Code Cards Wix archive",
    contextLabel: "Originally shared regarding Healing Code Cards",
    sortOrder: 39,
    productSlugs: LIVE_HEALING_CODE_CARD_SLUGS,
  },
];
