export type ApiRouteAuth =
  | "public"
  | "bearer"
  | "member"
  | "admin"
  | "internal"
  | "stripe-webhook"
  | "clerk-webhook";

export type ApiRouteValidation = "none" | "manual" | "service";

export interface ApiRouteManifestEntry {
  method: string;
  url: string;
  auth: ApiRouteAuth;
  validation: ApiRouteValidation;
  handlerFile: string;
  serviceRefs: string[];
}

export const API_ROUTE_MANIFEST: ApiRouteManifestEntry[] = [
  { method: "GET", url: "/", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: [] },
  { method: "GET", url: "/api", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: [] },
  { method: "GET", url: "/health", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: [] },
  { method: "GET", url: "/health/ephemeris", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: ["services/blueprint/swissEphemerisService.ts"] },
  { method: "GET", url: "/api/health", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: [] },
  { method: "GET", url: "/api/health/ephemeris", auth: "public", validation: "none", handlerFile: "routes/health.ts", serviceRefs: ["services/blueprint/swissEphemerisService.ts"] },
  { method: "POST", url: "/api/sync-user", auth: "bearer", validation: "service", handlerFile: "routes/sync-user.ts", serviceRefs: ["services/clerkIdentityService.ts", "services/userService.ts"] },
  { method: "GET", url: "/api/me", auth: "bearer", validation: "none", handlerFile: "routes/me.ts", serviceRefs: ["services/divin8/memberAccessService.ts"] },
  { method: "PATCH", url: "/api/me/profile", auth: "bearer", validation: "service", handlerFile: "routes/me.ts", serviceRefs: ["services/memberProfileService.ts"] },
  { method: "GET", url: "/api/me/recordings", auth: "bearer", validation: "none", handlerFile: "routes/me.ts", serviceRefs: ["services/orderRecordingService.ts"] },
  { method: "GET", url: "/api/mentoring-circle/me", auth: "bearer", validation: "none", handlerFile: "routes/mentoring-circle.ts", serviceRefs: ["services/mentoringCircleService.ts"] },
  { method: "POST", url: "/api/mentoring-circle/register", auth: "bearer", validation: "manual", handlerFile: "routes/mentoring-circle.ts", serviceRefs: ["services/mentoringCircleService.ts"] },
  { method: "GET", url: "/member/subscriptions", auth: "bearer", validation: "none", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "POST", url: "/member/subscriptions", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/membershipPurchaseService.ts"] },
  { method: "POST", url: "/member/subscriptions/:membershipId/confirm", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/membershipPurchaseService.ts"] },
  { method: "POST", url: "/member/subscriptions/:subscriptionType/:subscriptionId/cancel", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "POST", url: "/member/subscriptions/:subscriptionType/:subscriptionId/pause", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "GET", url: "/api/member/subscriptions", auth: "bearer", validation: "none", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "POST", url: "/api/member/subscriptions", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/membershipPurchaseService.ts"] },
  { method: "POST", url: "/api/member/subscriptions/:membershipId/confirm", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/membershipPurchaseService.ts"] },
  { method: "POST", url: "/api/member/subscriptions/:subscriptionType/:subscriptionId/cancel", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "POST", url: "/api/member/subscriptions/:subscriptionType/:subscriptionId/pause", auth: "bearer", validation: "service", handlerFile: "routes/memberships.ts", serviceRefs: ["services/memberSubscriptionsService.ts"] },
  { method: "POST", url: "/api/member/reports", auth: "bearer", validation: "service", handlerFile: "routes/reports.ts", serviceRefs: ["services/reportPurchaseService.ts"] },
  { method: "GET", url: "/api/member/reports", auth: "bearer", validation: "none", handlerFile: "routes/reports.ts", serviceRefs: ["services/reportPurchaseService.ts"] },
  { method: "GET", url: "/api/member/reports/:id", auth: "bearer", validation: "service", handlerFile: "routes/reports.ts", serviceRefs: ["services/reportPurchaseService.ts"] },
  { method: "GET", url: "/api/clients", auth: "admin", validation: "manual", handlerFile: "routes/clients.ts", serviceRefs: ["services/clientService.ts"] },
  { method: "GET", url: "/api/clients/:id", auth: "admin", validation: "manual", handlerFile: "routes/clients.ts", serviceRefs: ["services/clientService.ts"] },
  { method: "GET", url: "/api/reports", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "GET", url: "/api/reports/:id/docx", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/reportExport.ts"] },
  { method: "GET", url: "/api/reports/:id/pdf", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/reportExport.ts"] },
  { method: "DELETE", url: "/api/reports/:id", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "POST", url: "/api/blueprints/generate", auth: "admin", validation: "service", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/divin8/generateService.ts"] },
  { method: "POST", url: "/api/blueprints/:clientId/interpret", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/blueprint/index.ts", "services/reportFormat.ts"] },
  { method: "POST", url: "/api/blueprints/interpret/:reportId", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/blueprint/index.ts", "services/reportFormat.ts"] },
  { method: "GET", url: "/api/blueprints/reports/:id", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "GET", url: "/api/reports/:clientId", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "PATCH", url: "/api/reports/:id", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "POST", url: "/api/reports/:id/regenerate", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["services/blueprint/index.ts"] },
  { method: "POST", url: "/api/reports/:id/finalize", auth: "admin", validation: "manual", handlerFile: "routes/blueprints.ts", serviceRefs: ["routes/blueprints.ts"] },
  { method: "GET", url: "/api/booking-types", auth: "bearer", validation: "none", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingTypesService.ts"] },
  { method: "POST", url: "/api/bookings", auth: "bearer", validation: "manual", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingService.ts"] },
  { method: "GET", url: "/api/bookings", auth: "bearer", validation: "none", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingService.ts"] },
  { method: "GET", url: "/api/admin/bookings", auth: "admin", validation: "manual", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingService.ts"] },
  { method: "PATCH", url: "/api/admin/bookings/:id/confirm", auth: "admin", validation: "manual", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingService.ts"] },
  { method: "DELETE", url: "/api/bookings/:id", auth: "bearer", validation: "service", handlerFile: "routes/bookings.ts", serviceRefs: ["services/booking/bookingService.ts"] },
  { method: "GET", url: "/api/payments", auth: "bearer", validation: "none", handlerFile: "routes/payments.ts", serviceRefs: ["services/payments/paymentsService.ts"] },
  { method: "GET", url: "/api/admin/payments", auth: "admin", validation: "none", handlerFile: "routes/payments.ts", serviceRefs: ["services/payments/paymentsService.ts"] },
  { method: "POST", url: "/api/payments", auth: "bearer", validation: "manual", handlerFile: "routes/payments.ts", serviceRefs: ["services/payments/paymentsService.ts"] },
  { method: "POST", url: "/api/payments/:id/confirm", auth: "bearer", validation: "manual", handlerFile: "routes/payments.ts", serviceRefs: ["services/payments/paymentsService.ts"] },
  { method: "POST", url: "/api/payments/:id/refund", auth: "bearer", validation: "service", handlerFile: "routes/payments.ts", serviceRefs: ["services/payments/paymentsService.ts"] },
  { method: "GET", url: "/api/member/regeneration-subscription", auth: "bearer", validation: "none", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "POST", url: "/api/member/regeneration-subscription/checkout", auth: "bearer", validation: "service", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "POST", url: "/api/member/regeneration-subscription/confirm", auth: "bearer", validation: "service", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "GET", url: "/api/member/regeneration-subscription/check-ins", auth: "bearer", validation: "none", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "POST", url: "/api/member/regeneration-subscription/check-ins", auth: "bearer", validation: "service", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "POST", url: "/api/admin/regeneration-subscriptions/:userId/reconcile", auth: "admin", validation: "service", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "PATCH", url: "/api/admin/regeneration-subscriptions/:userId/override", auth: "admin", validation: "service", handlerFile: "routes/regeneration.ts", serviceRefs: ["services/regenerationSubscriptionService.ts"] },
  { method: "POST", url: "/api/images/upload", auth: "bearer", validation: "manual", handlerFile: "routes/images.ts", serviceRefs: ["services/physiognomyImageStorage.ts"] },
  { method: "GET", url: "/api/images/physiognomy/:imageAssetId", auth: "bearer", validation: "service", handlerFile: "routes/images.ts", serviceRefs: ["services/physiognomyImageStorage.ts"] },
  { method: "POST", url: "/api/divin8/run", auth: "member", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8EngineService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/divin8/prompt", auth: "admin", validation: "none", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/promptStore.ts"] },
  { method: "POST", url: "/api/divin8/prompt", auth: "admin", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/promptStore.ts"] },
  { method: "POST", url: "/api/divin8/generate", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/generateService.ts"] },
  { method: "GET", url: "/api/divin8/profiles", auth: "admin", validation: "none", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts"] },
  { method: "POST", url: "/api/divin8/profiles", auth: "admin", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts"] },
  { method: "DELETE", url: "/api/divin8/profiles/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts"] },
  { method: "POST", url: "/api/divin8/conversations", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "GET", url: "/api/divin8/conversations", auth: "admin", validation: "none", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "GET", url: "/api/divin8/conversations/search", auth: "admin", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "GET", url: "/api/divin8/conversations/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "GET", url: "/api/divin8/conversations/:id/timeline", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "POST", url: "/api/divin8/conversations/:id/message", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/chatService.ts", "services/divin8/conversationService.ts"] },
  { method: "DELETE", url: "/api/divin8/conversations/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "POST", url: "/api/divin8/conversations/:id/rename", auth: "admin", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "POST", url: "/api/divin8/export", auth: "admin", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts"] },
  { method: "GET", url: "/api/divin8/knowledge/sources", auth: "admin", validation: "none", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources/preview", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "GET", url: "/api/divin8/knowledge/sources/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources/:id/reprocess", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources/:id/replace", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources/:id/rollback", auth: "admin", validation: "manual", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/sources/:id/disable", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "DELETE", url: "/api/divin8/knowledge/sources/:id", auth: "admin", validation: "manual", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/concepts", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "PATCH", url: "/api/divin8/knowledge/concepts/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/overrides", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "PATCH", url: "/api/divin8/knowledge/overrides/:id", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/divin8/knowledge/test-retrieval", auth: "admin", validation: "service", handlerFile: "routes/divin8Knowledge.ts", serviceRefs: ["services/divin8/knowledge/knowledgeAdminService.ts"] },
  { method: "POST", url: "/api/member/divin8/conversations", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/member/divin8/profiles", auth: "member", validation: "none", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "POST", url: "/api/member/divin8/profiles", auth: "member", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "DELETE", url: "/api/member/divin8/profiles/:id", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/profilesService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/member/divin8/conversations", auth: "member", validation: "none", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/member/divin8/conversations/search", auth: "member", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/member/divin8/conversations/:id", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/member/divin8/conversations/:id/timeline", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "POST", url: "/api/member/divin8/conversations/:id/message", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/chatService.ts", "services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "DELETE", url: "/api/member/divin8/conversations/:id", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "POST", url: "/api/member/divin8/conversations/:id/rename", auth: "member", validation: "service", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "POST", url: "/api/member/divin8/export", auth: "member", validation: "manual", handlerFile: "routes/divin8.ts", serviceRefs: ["services/divin8/conversationService.ts", "services/divin8/memberAccessService.ts"] },
  { method: "GET", url: "/api/timezone/detect", auth: "public", validation: "none", handlerFile: "routes/timezone.ts", serviceRefs: ["services/timezoneDetectionService.ts"] },
  { method: "GET", url: "/api/places/autocomplete", auth: "public", validation: "manual", handlerFile: "routes/places.ts", serviceRefs: ["routes/places.ts"] },
  { method: "GET", url: "/api/places/:placeId", auth: "public", validation: "manual", handlerFile: "routes/places.ts", serviceRefs: ["routes/places.ts"] },
  { method: "POST", url: "/api/contact", auth: "public", validation: "manual", handlerFile: "routes/contact.ts", serviceRefs: ["services/contactService.ts"] },
  { method: "POST", url: "/api/member/contact", auth: "bearer", validation: "manual", handlerFile: "routes/contact.ts", serviceRefs: ["services/contactService.ts"] },
  { method: "GET", url: "/api/test/zoom-status", auth: "admin", validation: "none", handlerFile: "routes/zoom.ts", serviceRefs: ["routes/zoom.ts"] },
  { method: "POST", url: "/api/test/zoom-meeting", auth: "admin", validation: "service", handlerFile: "routes/zoom.ts", serviceRefs: ["services/zoomService.ts"] },
  { method: "GET", url: "/api/social/facebook/latest-post", auth: "public", validation: "none", handlerFile: "routes/social.ts", serviceRefs: ["services/facebookPageService.ts"] },
  { method: "GET", url: "/api/admin/dashboard", auth: "admin", validation: "none", handlerFile: "routes/dashboard.ts", serviceRefs: ["services/dashboardService.ts"] },
  { method: "GET", url: "/api/mentor-training", auth: "bearer", validation: "none", handlerFile: "routes/mentor-training.ts", serviceRefs: ["services/mentorTrainingService.ts"] },
  { method: "POST", url: "/api/mentor-training/checkout", auth: "bearer", validation: "manual", handlerFile: "routes/mentor-training.ts", serviceRefs: ["services/mentorTrainingService.ts", "services/paymentService.ts"] },
  { method: "PATCH", url: "/api/admin/mentor-training/:orderId/status", auth: "admin", validation: "manual", handlerFile: "routes/mentor-training.ts", serviceRefs: ["services/mentorTrainingService.ts"] },
  { method: "GET", url: "/api/courses/resonant-dowsing", auth: "bearer", validation: "none", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/courseEntitlementService.ts", "services/courses/resonantDowsingCourse.ts"] },
  { method: "GET", url: "/api/courses/resonant-dowsing/content", auth: "bearer", validation: "service", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/courseEntitlementService.ts", "services/courses/resonantDowsingCourse.ts"] },
  { method: "GET", url: "/api/courses/resonant-dowsing/lessons/:lessonId", auth: "bearer", validation: "service", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/courseProgressService.ts"] },
  { method: "POST", url: "/api/courses/resonant-dowsing/lessons/:lessonId/complete", auth: "bearer", validation: "service", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/courseProgressService.ts"] },
  { method: "POST", url: "/api/courses/resonant-dowsing/checkout", auth: "bearer", validation: "manual", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/courseEntitlementService.ts", "services/paymentService.ts"] },
  { method: "GET", url: "/api/admin/courses/resonant-dowsing/content", auth: "admin", validation: "none", handlerFile: "routes/courses.ts", serviceRefs: ["services/courses/resonantDowsingCourse.ts"] },
  { method: "GET", url: "/api/admin/courses/resonant-dowsing/price-diagnostics", auth: "admin", validation: "service", handlerFile: "routes/courses.ts", serviceRefs: ["config/courseBilling.ts"] },
  { method: "GET", url: "/api/admin/orders", auth: "admin", validation: "manual", handlerFile: "routes/orders.ts", serviceRefs: ["services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/archive", auth: "admin", validation: "manual", handlerFile: "routes/orders.ts", serviceRefs: ["services/ordersService.ts"] },
  { method: "GET", url: "/api/admin/orders/:orderId", auth: "admin", validation: "service", handlerFile: "routes/orders.ts", serviceRefs: ["services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/generate", auth: "admin", validation: "manual", handlerFile: "routes/orders.ts", serviceRefs: ["services/divin8ExecutionDispatcher.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/create-invoice", auth: "admin", validation: "service", handlerFile: "routes/orders.ts", serviceRefs: ["services/adminOrderInvoiceService.ts", "services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/recording", auth: "admin", validation: "service", handlerFile: "routes/orders.ts", serviceRefs: ["services/orderRecordingService.ts", "services/ordersService.ts"] },
  { method: "PATCH", url: "/api/admin/orders/:orderId/intake", auth: "admin", validation: "service", handlerFile: "routes/orders.ts", serviceRefs: ["services/adminOrderIntakeService.ts", "services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/refund", auth: "admin", validation: "service", handlerFile: "routes/orders.ts", serviceRefs: ["services/orderRefundService.ts", "services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/send-recovery-invoice", auth: "admin", validation: "manual", handlerFile: "routes/orders.ts", serviceRefs: ["services/reportRecoveryInvoiceService.ts", "services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/orders/:orderId/mark-paid", auth: "admin", validation: "manual", handlerFile: "routes/orders.ts", serviceRefs: ["services/adminOrderPaymentService.ts", "services/ordersService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/cancel-period-end", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/cancel-immediately", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/reactivate", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/pause", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/resume", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/extend-renewal", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/grant-courtesy-month", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/retry-payment", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/send-manual-invoice", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/regeneration/extend-access", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/regeneration/priority-support", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/regeneration/grace-period", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/regeneration/emergency-reactivate", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "POST", url: "/api/admin/subscriptions/:id/notes", auth: "admin", validation: "service", handlerFile: "routes/admin-subscriptions.ts", serviceRefs: ["services/adminSubscriptionLifecycleService.ts"] },
  { method: "GET", url: "/api/admin/notifications", auth: "admin", validation: "none", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/notificationRetryService.ts", "services/notifications/notificationSettingsService.ts"] },
  { method: "GET", url: "/api/admin/notifications/events", auth: "admin", validation: "none", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/events.ts", "services/notifications/samplePayloads.ts"] },
  { method: "POST", url: "/api/admin/notifications/test", auth: "admin", validation: "service", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/notificationService.ts"] },
  { method: "POST", url: "/api/admin/notifications/preview", auth: "admin", validation: "service", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/notificationPreview.ts"] },
  { method: "POST", url: "/api/admin/notifications/retry", auth: "admin", validation: "service", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/notificationRetryService.ts"] },
  { method: "PATCH", url: "/api/admin/notifications/settings", auth: "admin", validation: "service", handlerFile: "routes/admin-notifications.ts", serviceRefs: ["services/notifications/notificationSettingsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/summary", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/pageviews", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/events", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/referrers", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/overview", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "GET", url: "/api/admin/analytics/insights", auth: "admin", validation: "manual", handlerFile: "routes/analytics.ts", serviceRefs: ["services/analyticsService.ts"] },
  { method: "POST", url: "/api/internal/mentoring-circle/reminders", auth: "internal", validation: "manual", handlerFile: "routes/mentoring-circle.ts", serviceRefs: ["services/mentoringCircleService.ts", "services/notifications/notificationService.ts"] },
  { method: "GET", url: "/api/admin/seo", auth: "admin", validation: "manual", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoService.ts"] },
  { method: "POST", url: "/api/admin/seo", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoService.ts"] },
  { method: "PUT", url: "/api/admin/seo/:pageKey", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoService.ts"] },
  { method: "GET", url: "/api/admin/seo/audits", auth: "admin", validation: "none", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoAuditService.ts"] },
  { method: "POST", url: "/api/admin/seo/audits", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoAuditService.ts", "services/seoRecommendationService.ts", "services/seoReportService.ts"] },
  { method: "GET", url: "/api/admin/seo/audits/:id", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoAuditService.ts"] },
  { method: "GET", url: "/api/admin/seo/audits/:id/items", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoAuditService.ts"] },
  { method: "GET", url: "/api/admin/seo/recommendations", auth: "admin", validation: "manual", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoRecommendationService.ts"] },
  { method: "POST", url: "/api/admin/seo/recommendations/:id/approve", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReviewService.ts", "services/seoService.ts"] },
  { method: "POST", url: "/api/admin/seo/recommendations/:id/edit", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReviewService.ts", "services/seoService.ts"] },
  { method: "POST", url: "/api/admin/seo/recommendations/:id/reject", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReviewService.ts"] },
  { method: "POST", url: "/api/admin/seo/rollback/:changeId", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReviewService.ts", "services/seoService.ts"] },
  { method: "GET", url: "/api/admin/seo/reports", auth: "admin", validation: "none", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReportService.ts"] },
  { method: "GET", url: "/api/admin/seo/reports/:id", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReportService.ts"] },
  { method: "GET", url: "/api/seo/reports/:id/pdf", auth: "admin", validation: "service", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoReportService.ts", "services/reportExport.ts"] },
  { method: "POST", url: "/api/internal/seo/weekly-recommendations", auth: "internal", validation: "manual", handlerFile: "routes/seo.ts", serviceRefs: ["services/seoAuditService.ts", "services/seoRecommendationService.ts", "services/seoReportService.ts"] },
  { method: "GET", url: "/api/admin/promo-codes", auth: "admin", validation: "none", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "POST", url: "/api/admin/promo-codes", auth: "admin", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "PATCH", url: "/api/admin/promo-codes/:promoCodeId", auth: "admin", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "POST", url: "/api/admin/promo-codes/:promoCodeId/verify", auth: "admin", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "POST", url: "/api/admin/promo-codes/:promoCodeId/fix-sync", auth: "admin", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "POST", url: "/api/admin/promo-codes/test-checkout", auth: "admin", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "POST", url: "/api/promo-codes/validate", auth: "bearer", validation: "service", handlerFile: "routes/promoCodes.ts", serviceRefs: ["services/promoCodeService.ts"] },
  { method: "GET", url: "/api/shop/products", auth: "public", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopCatalog.ts"] },
  { method: "GET", url: "/api/shop/products/:slug/booklet", auth: "public", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopDownloadService.ts"] },
  { method: "GET", url: "/api/shop/products/:slug", auth: "public", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopCatalog.ts"] },
  { method: "GET", url: "/api/shop/media/:imageId", auth: "public", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "GET", url: "/api/shop/order/success", auth: "bearer", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopFulfillmentService.ts"] },
  { method: "POST", url: "/api/admin/shop/orders/:orderId/resend-fulfillment-email", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopFulfillmentService.ts"] },
  { method: "GET", url: "/api/shop/purchases", auth: "bearer", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopEntitlementService.ts"] },
  { method: "POST", url: "/api/shop/checkout", auth: "bearer", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopEntitlementService.ts", "services/paymentService.ts"] },
  { method: "POST", url: "/api/shop/downloads/:fileId/token", auth: "bearer", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopDownloadService.ts"] },
  { method: "GET", url: "/api/shop/downloads/:fileId", auth: "bearer", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopDownloadService.ts"] },
  { method: "GET", url: "/api/admin/shop/products", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "POST", url: "/api/admin/shop/products", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "GET", url: "/api/admin/shop/products/:productId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "PATCH", url: "/api/admin/shop/products/:productId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "POST", url: "/api/admin/shop/products/:productId/images", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "DELETE", url: "/api/admin/shop/images/:imageId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "POST", url: "/api/admin/shop/products/:productId/files", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "DELETE", url: "/api/admin/shop/files/:fileId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopAdminService.ts"] },
  { method: "GET", url: "/api/admin/shop/testimonials", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "GET", url: "/api/admin/shop/testimonial-settings", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "PATCH", url: "/api/admin/shop/testimonial-settings", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "POST", url: "/api/admin/shop/testimonials", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "GET", url: "/api/admin/shop/testimonials/:testimonialId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "PATCH", url: "/api/admin/shop/testimonials/:testimonialId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "DELETE", url: "/api/admin/shop/testimonials/:testimonialId/associations/:associationId", auth: "admin", validation: "service", handlerFile: "routes/shop.ts", serviceRefs: ["services/shop/shopTestimonials.ts"] },
  { method: "POST", url: "/api/create-checkout-session", auth: "bearer", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/paymentService.ts"] },
  { method: "POST", url: "/api/checkout-session/sync", auth: "bearer", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/payments/stripeWebhookService.ts"] },
  { method: "POST", url: "/api/admin/invoices", auth: "admin", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/payments/invoiceService.ts"] },
  { method: "POST", url: "/api/admin/invoices/:invoiceId/regenerate", auth: "admin", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/payments/invoiceService.ts"] },
  { method: "POST", url: "/api/stripe/webhook", auth: "stripe-webhook", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/payments/stripeWebhookService.ts"] },
  { method: "POST", url: "/api/webhook/stripe", auth: "stripe-webhook", validation: "service", handlerFile: "routes/stripe.ts", serviceRefs: ["services/payments/stripeWebhookService.ts"] },
  { method: "POST", url: "/api/webhook/clerk", auth: "clerk-webhook", validation: "service", handlerFile: "routes/clerk-webhook.ts", serviceRefs: ["services/userService.ts", "services/clerkIdentityService.ts"] },
  { method: "GET", url: "/api/admin/gmail/status", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailConnectionService.ts"] },
  { method: "GET", url: "/api/admin/gmail/oauth/start", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailConnectionService.ts"] },
  { method: "GET", url: "/api/admin/gmail/oauth/callback", auth: "public", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailConnectionService.ts"] },
  { method: "POST", url: "/api/admin/gmail/disconnect", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailConnectionService.ts"] },
  { method: "POST", url: "/api/admin/gmail/search", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "GET", url: "/api/admin/gmail/search-profiles", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "POST", url: "/api/admin/gmail/search-profiles", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "PATCH", url: "/api/admin/gmail/search-profiles/:profileId", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "DELETE", url: "/api/admin/gmail/search-profiles/:profileId", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "POST", url: "/api/admin/gmail/candidates/save", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "POST", url: "/api/admin/gmail/search-import", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/gmailSearchService.ts"] },
  { method: "GET", url: "/api/admin/email-contacts/exclusions", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/exclusionService.ts"] },
  { method: "POST", url: "/api/admin/email-contacts/exclusions", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/exclusionService.ts"] },
  { method: "DELETE", url: "/api/admin/email-contacts/exclusions/:id", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/exclusionService.ts"] },
  { method: "GET", url: "/api/admin/email-contacts", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "POST", url: "/api/admin/email-contacts", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "PATCH", url: "/api/admin/email-contacts/:id", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "DELETE", url: "/api/admin/email-contacts/:id", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "POST", url: "/api/admin/email-contacts/bulk-delete", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "POST", url: "/api/admin/email-contacts/import/preview", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/csvImportService.ts"] },
  { method: "POST", url: "/api/admin/email-contacts/import/commit", auth: "admin", validation: "service", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/csvImportService.ts"] },
  { method: "GET", url: "/api/admin/email-contacts/export", auth: "admin", validation: "none", handlerFile: "routes/adminEmails.ts", serviceRefs: ["services/emailList/contactService.ts"] },
  { method: "GET", url: "/api/admin/ads/status", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsConnectionService.ts"] },
  { method: "GET", url: "/api/admin/ads/google/oauth/start", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsOAuthService.ts"] },
  { method: "GET", url: "/api/admin/ads/google/oauth/callback", auth: "public", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsOAuthService.ts"] },
  { method: "POST", url: "/api/admin/ads/google/disconnect", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsOAuthService.ts"] },
  { method: "GET", url: "/api/admin/ads/reporting/summary", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsReportingService.ts"] },
  { method: "GET", url: "/api/admin/ads/reporting/campaigns", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/googleAdsReportingService.ts"] },
  { method: "GET", url: "/api/admin/ads/agent/health", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsAgentService.ts"] },
  { method: "POST", url: "/api/admin/ads/agent/health/test", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsAgentService.ts"] },
  { method: "PATCH", url: "/api/admin/ads/agent/settings", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsSettingsService.ts"] },
  { method: "POST", url: "/api/admin/ads/agent/chat", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsAgentService.ts"] },
  { method: "GET", url: "/api/admin/ads/agent/conversations", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsConversationService.ts"] },
  { method: "POST", url: "/api/admin/ads/agent/conversations", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsConversationService.ts"] },
  { method: "GET", url: "/api/admin/ads/agent/conversations/:id", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsConversationService.ts"] },
  { method: "POST", url: "/api/admin/ads/agent/conversations/:id/clear", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsConversationService.ts"] },
  { method: "GET", url: "/api/admin/ads/divin8-knowledge", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/adsKnowledgeService.ts"] },
  { method: "GET", url: "/api/admin/ads/pma/projects", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/pma/pmaService.ts"] },
  { method: "GET", url: "/api/admin/ads/pma/workspace", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/pma/pmaService.ts"] },
  { method: "POST", url: "/api/admin/ads/pma/analyze", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/pma/pmaService.ts"] },
  { method: "GET", url: "/api/admin/ads/pma/campaigns", auth: "admin", validation: "none", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/pma/pmaService.ts"] },
  { method: "POST", url: "/api/admin/ads/pma/campaigns", auth: "admin", validation: "service", handlerFile: "routes/adminAds.ts", serviceRefs: ["services/ads/pma/pmaService.ts"] },
];
